applications/calificaciones/urls.py
from django.urls import path
from . import views

app_name = 'calificaciones_app'

urlpatterns = [
    path("control-calificaciones/", views.ControlCalificaciones.as_view(),
         name="control_calificaciones"),
    path("registro-credito/", views.ViewRegistroCreditos.as_view(),
         name="registro_credito"),
    path("estatus-credito/", views.ViewCreditosStatus.as_view(),
         name="estatus_credito"),
    path("estatus-credito-estatico/", views.ViewCreditosStatusEstatico.as_view(),
         name="estatus_credito_estatico"),
    path("registro-pagos/", views.RegistroPagos.as_view(), name="registro_pagos"),
    path('obtener_monto_total/', views.obtener_monto_total,
         name='obtener_monto_total'),
    # path('get_estatus_credito_data/<int:num_contrato>/', views.GetEstatusCreditoDataView.as_view(), name='get_estatus_credito_data'),
    # path("estatus-credito/",views.view_creditos_status,name="estatus_credito"),
]

applications/dashboard/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard_app'

urlpatterns = [
    path("",views.DashboardView.as_view(), name="index"),
    #path("crear_simulador/<int:user_id>/", views.DashboardView.as_view(), name="crear_simulador"),
    path('preguntas-respuestas/',views.PreguntasRespuestas.as_view(),name='preguntas_respuestas'),
    path('productos/productos-gral/',views.ProductosView.as_view(),name='productos_gral'),
    
    ##### Grupal ####
    path("dashboard/productos/nuevo-grupal/",views.CreateGrupal.as_view(),name="nuevo_grupal"),
    path('dashboard/productos/editar-grupal/<int:pk>/',views.EditarGrupal.as_view(),name='editar_grupal'),
    ##### Grupal ####
    
    ##### producto #####
    path("dashboard/productos/nuevo-producto/",views.CreateProductosView.as_view(),name="nuevo_productos"),
    path('dashboard/productos/editar-productos/<int:pk>/',views.EditarProducto.as_view(),name='editar_productos'),
    path('dashboard/productos/eliminar-productos/<int:pk>/',views.EliminarProducto.as_view(),name='eliminar_productos'),
    
    ##### producto #####
    ##### plazo #####
    path("dashboard/plazos/nuevo-plazo/", views.CreatePlazoView.as_view(), name="nuevo_plazo"),
    path("dashboard/plazos/editar-plazo/<int:pk>/", views.EditarPlazoView.as_view(), name="editar_plazo"),
    path("dashboard/plazos/eliminar-plazo/<int:pk>", views.EliminarPlazo.as_view(), name="eliminar_plazo"),
    ##### plazo #####
    
    ##### obtener el interes ###
    path('obtener-interes/', views.obtener_interes, name='obtener_interes'),
    path('obtener-mora/', views.obtener_moratorio, name='obtener_mora'),
    path('obtener-plazo/', views.obtener_plazo, name='obtener_plazo'),
    ##### obtener el interes ###
    
    path("editar-usuario/<int:pk>", views.EditarUsuarioUsers.as_view(), name="editar_usuario"),
    path("terminos/", views.AvisoPrivacidad.as_view(), name="terminos_condiciones"),
    path("terminos-condiciones/", views.TerminosCondiciones.as_view(), name="terminos_condiciones_2"),
    
    path('pdf-documento/', views.PdfDocument.as_view(), name='pdf_documento'),
    
    path('generar_pdf/', views.PdfDocumentGrupal.as_view(), name='generar_pdf'),
    
    path('mifiel/', views.crearMifiel, name='mifiel'),
    
    path('info-buro/',views.InfoBuro.as_view(),name='info-buro'),
    path('guardar-firma/<int:user_id>/', views.guardar_firma, name='guardar_firma'),
    
    path('nuevo_prestamo/', views.PrestamoCreateView.as_view(), name='nuevo_prestamo'),
    path('sim_prestamo/', views.SimPrestamoCreateView.as_view(), name='sim_prestamo'),
    path('simulador_pruebas/', views.SimuladorPruebaCreateView.as_view(), name='simulador_pruebas'),
    path('pruebas_simula/', views.PruebaSimulaView.as_view(), name='pruebas_simula'),
    path('dashboard/get_nombre_producto/<int:prestamo_id>/', views.GetNombreProductoView.as_view(), name='get_nombre_producto'),
    
    path('csv/', views.DatoView.as_view(), name='csv'),
    path('csv/upload', views.subir_csv, name='subir_csv'),
    
    #path('dashboard/get_nombre_producto/<int:prestamo_id>/', views.GetNombreProductoView.as_view(), name='get_nombre_producto'),
    #path('index/info-prestamo/', views.obtener_informacion_prestamo, name='info_prestamo'),
    #path('dashboard/obtener_detalles_prestamo/', views.ObtenerDetallesPrestamoView.as_view(), name='obtener_detalles_prestamo'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/landing/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'landing_app'

urlpatterns = [
    path('',views.landing_view, name='landing')
]

applications/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'user_app'


urlpatterns = [
    path('registro/', views.RegistrarUsuario.as_view(), name='registro'),
    path('lista-usuarios/',views.ListaUsuarios.as_view(),name='lista_usuarios'),
    path('eliminar-usuarios/<int:pk>/',views.EliminarUsuarios.as_view(),name='eliminar_usuarios'),
    path('editar-usuarios/<int:pk>/',views.EditarUsuario.as_view(),name='editar_usuarios'),
    path('ubicacion/',views.guardar_ubicacion,name='ubicacion'),
    path('solicitud/<int:user_id>/', views.SolicitudCheck.as_view(), name='solicitud'),
    path('clientes/', views.ClientesAll.as_view(), name='clientes'),
    path('grupal/', views.GrupalCredito.as_view(), name='grupal'),
    path('correo-grupo-credito/', views.correo_grupo_credito, name='correo_grupo_credito'),
    
    path('obtener-monto/', views.obtener_monto, name='obtener_monto'),
    path('formulario-credito/', views.FormularioCreditoGrupal.as_view(), name='formulario_credito'),
    
    path('buro-credito/', views.ModalBruroCredito.as_view(), name='buro_credito'),
    path('aviso-privacidad-grupal/', views.AvisoPrivacidadGrupal.as_view(), name='aviso_privacidad_grupal'),
    path('registrar-credito/', views.RegistrarCreditoView.as_view(), name='registrar_credito'),
    path('carga-masiva/', views.upload_excel_view, name='carga_masiva'),
    
    #path('crear_simulador/<int:user_id>/', views.tu_vista_crear_simulador, name='crear_simulador'),
    
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
# from yaab_corp.view import index_view
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path('solicitud/',include('applications.credit_personal.urls')),
    path("calificaciones/", include('applications.calificaciones.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>
      {% block title %}{% endblock title %} | Adminto - Responsive Admin
      Dashboard Template
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      content="A fully featured admin theme which can be used to build CRM, CMS, etc."
      name="description"
    />
    <meta content="coderthemes" name="author" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

    <!-- App css -->

    <link
      href="{% static 'css/app.css' %}"
      rel="stylesheet"
      type="text/css"
      id="app-style"
    />

    <!-- icons -->
    <link
      href="{% static 'css/icons.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    {% block css %} {% block extra_css %} {% endblock extra_css %}
    <!---->
    {% include "partials/head-css.html" %} {% endblock css %}
  </head>

  <body
    class="loading"
    data-layout-color="light"
    data-layout-mode="default"
    data-layout-size="fluid"
    data-topbar-color="light"
    data-leftbar-position="fixed"
    data-leftbar-color="light"
    data-leftbar-size="default"
    data-sidebar-user="true"
  >
    <div id="wrapper">
      {% block topbar %} {% endblock topbar %}
      <!---->

      {%include "partials/left-sidebar.html" %}

      <div class="content-page">
        <div class="content">
          <div class="container-fluid">
            {% block content %} {% endblock content %}
          </div>
        </div>
      </div>
    </div>

    {% include "partials/right-sidebar.html" %} {% include
    "partials/vendor.html" %} {% block extra_js %} {% endblock extra_js %}

    <!-- App js-->
    <script src="{% static 'js/app.min.js' %}"></script>
  </body>
</html>

templates/partials/footer.html
<!-- Footer Start -->
<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <script>
          document.write(new Date().getFullYear());
        </script>
        &copy; Inversiones y Servicios Financieros<a href="">YAAB</a>
      </div>
      <div class="col-md-6">
        <div class="text-md-end footer-links d-none d-sm-block">
          <a href="{% url 'landing_app:landing' %}">Inicio</a>
          <!-- <a href="javascript:void(0);">Help</a>
          <a href="javascript:void(0);">Contact Us</a> -->
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- end Footer -->

templates/partials/head-css.html
{% load static %}
<!-- App css -->
<link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

<!-- icons -->
<link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />

templates/partials/layout-horizontal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-mode="horizontal" data-layout-color="light" data-layout-size="fluid"
      data-topbar-color="dark" data-leftbar-position="fixed">


<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/topbar-dark.html" %}
    {% include "partials/horizontal-nav.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/right-sidebar.html" %}

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

templates/partials/layout-preloader.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-color="light" data-layout-mode="default" data-layout-size="fluid"
      data-topbar-color="light" data-leftbar-position="fixed" data-leftbar-color="light" data-leftbar-size='default'
      data-sidebar-user='true'>

        <!-- Pre-loader -->
        <div id="preloader">
            <div id="status">
                <div class="spinner">Loading...</div>
            </div>
        </div>
        <!-- End Preloader-->

<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/left-sidebar.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/right-sidebar.html" %}

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

templates/partials/layout-vertical.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock title %} | Yaab Fianciera</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      content="A fully featured admin theme which can be used to build CRM, CMS, etc."
      name="description"
    />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/landing/yaab_corp.png' %}" />
    <link rel="stylesheet" href="{% static 'css/loading.css' %}" />

    {% block css %} {% block extra_css %} {% endblock extra_css %}
    <!---->
    {% include "partials/head-css.html" %} {% endblock css %}

   

    <div id="loading-container">
        <div class="loader"></div>
    </div>

    
  </head>

  <body
    class="loading"
    data-layout-color="light"
    data-layout-mode="default"
    data-layout-size="fluid"
    data-topbar-color="light"
    data-leftbar-position="fixed"
    data-leftbar-color="dark"
    data-leftbar-size="default"
    data-sidebar-user="true"
  >
    <div id="wrapper">
      {% block topbar %} {% endblock topbar %}
      <!---->
      {% include "partials/left-sidebar.html" %}

      <div class="content-page">
        <div class="content">
          <div class="container-fluid">
            {% block content %} {% endblock content %}
          </div>
        </div>

        {% include "partials/footer.html" %}
      </div>
    </div>

    {% include "partials/right-sidebar.html" %}
    <!---->
    {% include "partials/vendor.html" %} {% block extra_js %}
    <!---->
    {% endblock extra_js %}

    <!-- App js-->
    <script src="{% static 'js/app.min.js' %}"></script>
    <script src="{% static 'js/loading.js' %}"></script>
  </body>
</html>

templates/partials/left-sidebar.html
{% load static %}
{% load has_group %}

<style>
  .texto-blanco {
    color: #c5c9cd;
  }

  .texto-blanco:hover {
    color: #ffffff;
  }
</style>
<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">
  <div class="h-100" data-simplebar>
    <!-- User box -->
    <div class="user-box text-center mb-3">
     {% if user.imagen_perfil %}
        <img
          src="{{ user.imagen_perfil.url }}"
          alt="user-img"
          title="Mat Helme"
          class="rounded-circle img-thumbnail avatar-md"
        />
      {% else %}
       <!-- static 'images/landing/yaab_corp.png'  -->
        <img
          src="{% static 'images/landing/yaab_corp.png'%}"
          alt="user-img"
          title="Mat Helme"
          class="rounded-circle img-thumbnail avatar-md"
        />
      {% endif %}

      <div class="dropdown ">
        <a
          href="#"
          class="user-name dropdown-toggle h5 mt-2 mb-1 d-block"
          data-bs-toggle="dropdown"
          aria-expanded="false"
          >{{user.first_name}} {{user.last_name}}</a
        >
        <div class="dropdown-menu user-pro-dropdown mx-auto">
          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item d-none">
            <i class="fe-user me-1"></i>
            <span>My Account</span>
          </a>

          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item d-none">
            <i class="fe-settings me-1"></i>
            <span>Settings</span>
          </a>

          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item d-none">
            <i class="fe-lock me-1"></i>
            <span>Lock Screen</span>
          </a>

          <!-- item-->
          <a href="{% url 'account_logout' %}" class="btn btn-outline-secondary border border-light  notify-item">
            <i class="fe-log-out me-1"></i>
            <span>Cerrar Sesion</span>
          </a>
        </div>
      </div>

      <p class="text-muted left-user-info">{{user.rfc}}</p>

      <ul class="list-inline d-none">
        <li class="list-inline-item">
          <a href="#" class="text-muted left-user-info">
            <i class="mdi mdi-cog"></i>
          </a>
        </li>

        <li class="list-inline-item">
          <a href="#">
            <i class="mdi mdi-power"></i>
          </a>
        </li>
      </ul>
    </div>

    <!--- Sidemenu -->
    <div id="sidebar-menu">
      <ul id="side-menu">
        <li class="menu-title">Panel de administración</li>

        <li>
          <a href="{% url 'dashboard_app:index' %}">
            <!-- <iconify-icon icon="mdi:view-dashboard"></iconify-icon> -->
            <i class="mdi mdi-home" style="color: #ffff"></i>
            <!-- <span class="badge rounded-pill float-end">9+</span> -->
            <span class="texto-blanco"> Inicio </span>
          </a>
        </li>

        <!-- if request.user|has_group:'Admin' -->
        {% if request.user|has_group:'Administrador General' or request.user|has_group:'Analista Credito' or request.user|has_group:'Coordinador Cuenta' or request.user|has_group:'Cobranza'  %}
        <li class="menu-title mt-2">Administrativo</li>
        {% endif %}
        {% if request.user|has_group:'Administrador General' or request.user|has_group:'Analista Credito' %}
        <li>
          <a href="#sideBarProductos" data-bs-toggle="collapse">
            <i class="mdi mdi-hand-pointing-right" style="color: #ffff"></i>
            <span class="texto-blanco"> Productos </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarProductos">
            <ul class="nav-second-level">
              
              <li>
                <!--url 'inbox'-->
                
                <a href="{% url 'dashboard_app:productos_gral' %}">
                  <span class="texto-blanco">Alta de productos</span>
                </a>
              </li>
              
              
            </ul>
          </div>
        </li>
        {% endif  %}


        {% if request.user|has_group:'Administrador General' or request.user|has_group:'Coordinador Cuenta'%}
        <li>
          <a href="#sideBarUsuarios" data-bs-toggle="collapse">
            <i class="mdi mdi-account-multiple" style="color: #ffff"></i>
            <span class="texto-blanco"> Control de usuarios </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarUsuarios">
            <ul class="nav-second-level">
              
              <li>
                <!--url 'templates'-->
                <a href="{% url 'user_app:lista_usuarios' %}"> <span class="texto-blanco">Usuarios</span></a>
              </li>

              
              <li class="d-none">
                <!--url 'templates'-->
                <a href="{% url 'user_app:clientes' %}"> <span class="texto-blanco">Clientes</span></a>
              </li>
            
              
              
            </ul>
          </div>
        </li>
        {% endif  %}

        



        {% if request.user|has_group:'Administrador General' or request.user|has_group:'Cobranza' %}
        <li>
          <a href="#sideBarAdministrativo" data-bs-toggle="collapse">
            <i class="mdi mdi-credit-card-multiple" style="color: #ffff"></i>
            <span class="texto-blanco"> Control de créditos </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarAdministrativo">
            <ul class="nav-second-level">
              
              
               <li>
                <!--url 'templates'-->
                <a href="{% url 'user_app:registrar_credito' %}"> <span class="texto-blanco">Registrar crédito</span></a>
              </li>
               <li>
                <!--url 'templates'-->
                <a href="{% url 'credit_personal_app:bandeja_solicitud_html' %}"> <span class="texto-blanco">Autorización</span></a>
              </li>
              
              
              
              
              <li >
                <!--url 'templates'-->
                <a href="{% url 'calificaciones_app:control_calificaciones' %}"> <span class="texto-blanco">Calificaciones</span></a>
              </li>

              <li >
                <!--url 'templates'-->
                <a href="{% url 'calificaciones_app:estatus_credito' %}"> <span class="texto-blanco">Aplicación de pago</span></a>
              </li>

             
              <li class="d-none">
                <!--url 'templates'-->
                <a href="{% url 'calificaciones_app:registro_pagos' %}"> <span class="texto-blanco">Registro pagos</span></a>
              </li>
              
            </ul>
          </div>
        </li>
        {% endif %}

        {% if request.user|has_group:'Administrador General' or request.user|has_group:'Analista Credito' %}
        <li>
          <a href="#sideBarConsultas" data-bs-toggle="collapse">
            <i class="mdi mdi-hand-pointing-right" style="color: #ffff"></i>
            <span class="texto-blanco"> Consultas </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarConsultas">
            <ul class="nav-second-level">

              <li>
                <!--url 'templates'-->
                <a href="{% url 'credit_personal_app:confirmados' %}"> <span class="texto-blanco">Solicitudes</span></a>
              </li>
              
               <li>
                <!--url 'templates'-->
                <a href="{% url 'calificaciones_app:estatus_credito_estatico' %}"> <span class="texto-blanco">Estatus Creditos</span></a>
              </li>
              
              
            </ul>
          </div>
        </li>
        {% endif  %}

        <!-- endif -->
        {% if request.user|has_group:'Administrador General' or request.user|has_group:'Analista Credito' or request.user|has_group:'Coordinador Cuenta' or request.user|has_group:'Cobranza'  %}
        <li class="menu-title mt-2">General usuarios</li>
        {% endif %}

        <li>
          <a href="#sidebarUsuarios" data-bs-toggle="collapse">
            <i class="mdi mdi-help-circle" style="color: #ffff"></i>
            <span class="texto-blanco"> Ayuda </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sidebarUsuarios">
            <ul class="nav-second-level">
              <li>
                <!--url 'inbox'-->
                <a href="{%url 'dashboard_app:preguntas_respuestas'%}">
                  <span class="texto-blanco">Preguntas y repuestas</span>
                </a>
              </li>

              
               <li>
                <!--url 'templates'-->
                <a href="{% url 'dashboard_app:info-buro' %}"> <span class="texto-blanco">Buró de Crédito</span></a>
              </li>
              
              
            </ul>
          </div>
        </li>
      </ul>
    </div>
    <!-- End Sidebar -->

    <div class="clearfix"></div>
  </div>
  <!-- Sidebar -left -->
</div>
<!-- Left Sidebar End -->

templates/partials/title-meta.html
{% load static %}
<meta charset="utf-8" />
<title>{{title}} </title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
<meta content="Coderthemes" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- App favicon -->
<link rel="shortcut icon" href="{% static 'images/landing/yaab_corp.png' %}">

templates/partials/vendor.html
{% load static %}
<!-- Vendor -->
<script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'libs/node-waves/waves.min.js' %}"></script>
<script src="{% static 'libs/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'libs/jquery.counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'libs/feather-icons/feather.min.js' %}"></script>