applications/dashboard/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard_app'

urlpatterns = [
    path("",views.DashboardView.as_view(), name="index"),
    #path("crear_simulador/<int:user_id>/", views.DashboardView.as_view(), name="crear_simulador"),
    path('preguntas-respuestas/',views.PreguntasRespuestas.as_view(),name='preguntas_respuestas'),
    path('productos/productos-gral/',views.ProductosView.as_view(),name='productos_gral'),
    
    ##### Grupal ####
    path("dashboard/productos/nuevo-grupal/",views.CreateGrupal.as_view(),name="nuevo_grupal"),
    path('dashboard/productos/editar-grupal/<int:pk>/',views.EditarGrupal.as_view(),name='editar_grupal'),
    ##### Grupal ####
    
    ##### producto #####
    path("dashboard/productos/nuevo-producto/",views.CreateProductosView.as_view(),name="nuevo_productos"),
    path('dashboard/productos/editar-productos/<int:pk>/',views.EditarProducto.as_view(),name='editar_productos'),
    path('dashboard/productos/eliminar-productos/<int:pk>/',views.EliminarProducto.as_view(),name='eliminar_productos'),
    
    ##### producto #####
    ##### plazo #####
    path("dashboard/plazos/nuevo-plazo/", views.CreatePlazoView.as_view(), name="nuevo_plazo"),
    path("dashboard/plazos/editar-plazo/<int:pk>/", views.EditarPlazoView.as_view(), name="editar_plazo"),
    path("dashboard/plazos/eliminar-plazo/<int:pk>", views.EliminarPlazo.as_view(), name="eliminar_plazo"),
    ##### plazo #####
    
    ##### obtener el interes ###
    path('obtener-interes/', views.obtener_interes, name='obtener_interes'),
    path('obtener-mora/', views.obtener_moratorio, name='obtener_mora'),
    path('obtener-plazo/', views.obtener_plazo, name='obtener_plazo'),
    ##### obtener el interes ###
    
    path("editar-usuario/<int:pk>", views.EditarUsuarioUsers.as_view(), name="editar_usuario"),
    path("terminos/", views.AvisoPrivacidad.as_view(), name="terminos_condiciones"),
    path("terminos-condiciones/", views.TerminosCondiciones.as_view(), name="terminos_condiciones_2"),
    
    path('pdf-documento/', views.PdfDocument.as_view(), name='pdf_documento'),
    
    path('generar_pdf/', views.PdfDocumentGrupal.as_view(), name='generar_pdf'),
    
    path('mifiel/', views.crearMifiel, name='mifiel'),
    
    path('info-buro/',views.InfoBuro.as_view(),name='info-buro'),
    path('guardar-firma/<int:user_id>/', views.guardar_firma, name='guardar_firma'),
    
    path('nuevo_prestamo/', views.PrestamoCreateView.as_view(), name='nuevo_prestamo'),
    path('sim_prestamo/', views.SimPrestamoCreateView.as_view(), name='sim_prestamo'),
    path('simulador_pruebas/', views.SimuladorPruebaCreateView.as_view(), name='simulador_pruebas'),
    path('pruebas_simula/', views.PruebaSimulaView.as_view(), name='pruebas_simula'),
    path('dashboard/get_nombre_producto/<int:prestamo_id>/', views.GetNombreProductoView.as_view(), name='get_nombre_producto'),
    
    path('csv/', views.DatoView.as_view(), name='csv'),
    path('csv/upload', views.subir_csv, name='subir_csv'),
    
    #path('dashboard/get_nombre_producto/<int:prestamo_id>/', views.GetNombreProductoView.as_view(), name='get_nombre_producto'),
    #path('index/info-prestamo/', views.obtener_informacion_prestamo, name='info_prestamo'),
    #path('dashboard/obtener_detalles_prestamo/', views.ObtenerDetallesPrestamoView.as_view(), name='obtener_detalles_prestamo'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
# from yaab_corp.view import index_view
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path('solicitud/',include('applications.credit_personal.urls')),
    path("calificaciones/", include('applications.calificaciones.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/dashboard/views.py
from django.forms import BaseModelForm
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.views import View
from django.views.decorators.http import require_POST,require_GET
from django.db import IntegrityError
from django.http import HttpResponseBadRequest

import base64
from django.core.files.base import ContentFile

from django.views.generic import TemplateView
from django.views.generic import ListView,UpdateView,CreateView,DeleteView
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404

from django.urls import reverse_lazy,reverse
from django.template.loader import get_template
from django.http import FileResponse
from datetime import datetime
import locale

from .models import Productos,Plazo,Simulador,ImageYaab,ProductoCreditoGrupal,Prestamo,SimuladorPrueba,PruebaSimula,Dato
from .forms import ProductosForm,PlazoPagoForm,SimuladorForm,FormProductosGrupal,PrestamoForm,SimPruebas,SimuladorPruebaForm,PruebaSimulaForms,DatoForm

from applications.users.models import User,GrupoCreditoPersonal,CorreosCreditoGrupal
from applications.users.mixins import ValidarPermisosMixin
from applications.users.forms import UserChangeForm
from .utils import render_to_pdf,crearMifiel
from mifiel import Document, Client

import uuid
import logging



# Create your views here.from django.views.generic.base import TemplateView
class DashboardView(LoginRequiredMixin,CreateView):
    model = SimuladorPrueba
    template_name="dashboard/index.html"
    form_class = SimPruebas #SimuladorForm
    success_url = reverse_lazy('dashboard_app:index')
    
    def form_valid(self, form):
        # Asignar el usuario logeado al campo usuario_user antes de guardar
        form.instance.usuario_user = self.request.user
        return super().form_valid(form)
    
class GetNombreProductoView(View):
    def get(self, request, prestamo_id, *args, **kwargs):
        prestamo = get_object_or_404(Prestamo, id=prestamo_id)
        nombre_producto = prestamo.nombre_producto
        tipo_prestamo_nombre = prestamo.tipo_prestamo.tipo_credito if prestamo.tipo_prestamo else None
        tipo_periodo = prestamo.tipo_periodo.periodo_credito if prestamo.tipo_periodo else None
        plazo = prestamo.plazo
        interes_ordinario = prestamo.interes_ordinario
        interes_moratorio = prestamo.interes_moratorio
        pago_mensual = prestamo.pago_mensual
        return JsonResponse({'nombre_producto': nombre_producto,'tipo_prestamo':tipo_prestamo_nombre,'tipo_periodo': tipo_periodo,'plazo':plazo,'interes_ordinario':interes_ordinario,'interes_moratorio':interes_moratorio,'pago_mensual':pago_mensual})





##el bueno##
# class DashboardView(CreateView):
#     template_name="dashboard/index.html"
#     form_class = SimuladorForm
#     success_url = reverse_lazy('dashboard_app:index')
    
#     def get_context_data(self, **kwargs):
#         context = super(DashboardView, self).get_context_data(**kwargs)
#         user = self.kwargs.get('pk')
#         #user_id = self.kwargs.get('pk')
#         #user_id = self.kwargs.get('user_id')
#         #print("Valor de user_id:", user_id)
#         context['pk'] = user
#         context['simula'] = Simulador.objects.filter(id=user)
        

#         return context
    
#     def form_valid(self, form):
        
#         # user_id = self.kwargs.get('user_id')
#         # usuario_actual = get_object_or_404(User, pk=user_id)
        
#         tipo_credito = form.cleaned_data['tipo_credito']
#         plazo_nombre = form.cleaned_data['plazo_nombre']
#         amount = form.cleaned_data['amount']
#         interest_rate = form.cleaned_data['interest_rate']
#         term = form.cleaned_data['term']

#         # Realiza el cálculo
#         monthly_interest_rate = (interest_rate / 12) / 100
#         num_payments = term * 12
#         monthly_payment = (amount * monthly_interest_rate) / (1 - (1 + monthly_interest_rate) ** -num_payments) + (amount / 12) 

#         # Guarda los resultados en la base de datos o donde lo necesites
#         # Aquí se asume que hay un modelo Loan para guardar los resultados
        
#         loan = Simulador(amount=amount, tipo_credito = tipo_credito,plazo_nombre=plazo_nombre, interest_rate=interest_rate, term=term, monthly_payment=monthly_payment)
#         loan.save()
        
#         # url_crear_simulador = reverse('crear_simulador', kwargs={'user_id': user_id})
        
#         # # Guarda el simulador asociándolo al usuario actual
#         # simulador = Simulador.objects.create(
#         #     tipo_credito=tipo_credito,
#         #     plazo_nombre=plazo_nombre,
#         #     amount=amount,
#         #     interest_rate=interest_rate,
#         #     term=term,
#         #     monthly_payment=monthly_payment
#         # )
#         # usuario_actual.simulador = simulador
#         # usuario_actual.save()

#         response_data = {'monthly_payment': monthly_payment}
#         return JsonResponse(response_data)

# class DashboardView(LoginRequiredMixin,CreateView):
#     model = SimuladorPrueba
#     template_name="dashboard/index.html"
#     form_class = SimPruebas #SimuladorForm
#     success_url = reverse_lazy('dashboard_app:index')
    
    
#     def form_valid(self, form):
#         # Guarda la instancia de SimuladorPrueba y asocia el simulador al usuario
#         response = super().form_valid(form)
#         self.object.usuario = self.request.user
#         self.object.save()

#         # Puedes agregar un mensaje si lo deseas
#         messages.success(self.request, 'Simulador guardado exitosamente.')

#         return response
    
    
         
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['montos_prestamo'] = Prestamo.objects.values_list('monto', flat=True)
#         context['prestamos'] = Prestamo.objects.select_related('tipo_prestamo').all().order_by('id')
#         context['tabla_prestamos'] = Prestamo.objects.all()
        
#         return context

#checar esto despues
# class GetNombreProductoView(View):
#     def get(self, request, prestamo_id, *args, **kwargs):
#         prestamo = get_object_or_404(Prestamo, id=prestamo_id)
#         nombre_producto = prestamo.nombre_producto
#         tipo_prestamo_nombre = prestamo.tipo_prestamo.tipo_credito if prestamo.tipo_prestamo else None
#         return JsonResponse({'nombre_producto': nombre_producto,'tipo_prestamo':tipo_prestamo_nombre})
    
    
    # def post(self, request, *args, **kwargs):
    #     try:
    #         # Puedes procesar el índice y realizar otras acciones aquí
    #         selected_index = int(request.POST.get('selected_index'))

    #         # Intenta acceder a la instancia de Prestamo según el índice
    #         prestamo_instance = Prestamo.objects.get(id=selected_index)

    #         # Crea una instancia de tu modelo y guárdala
    #         simulador_prueba = SimuladorPrueba(nombre_prestamo=prestamo_instance)
    #         simulador_prueba.save()

    #         return JsonResponse({'success': True})
    #     except Prestamo.DoesNotExist:
    #         # Maneja el caso donde el Prestamo con el índice dado no existe
    #         return JsonResponse({'success': False, 'error': 'Prestamo no encontrado'}, status=404)
    #     except Exception as e:
    #         # Maneja otras excepciones generales
    #         return JsonResponse({'success': False, 'error': str(e)}, status=500)
    
    # def form_valid(self, form):
    #     try:
    #         # Puedes procesar el índice y realizar otras acciones aquí
    #         selected_index = int(self.request.POST.get('selected_index'))

    #         # Intenta acceder a la instancia de Prestamo según el índice
    #         prestamo_instance = Prestamo.objects.get(id=selected_index)

    #         # Crea una instancia de tu modelo y guárdala
    #         simulador_prueba = SimuladorPrueba(nombre_prestamo=prestamo_instance)
    #         simulador_prueba.save()

    #         return JsonResponse({'success': True})
    #     except Prestamo.DoesNotExist:
    #         # Maneja el caso donde el Prestamo con el índice dado no existe
    #         return JsonResponse({'success': False, 'error': 'Prestamo no encontrado'}, status=404)
    #     except Exception as e:
    #         # Maneja otras excepciones generales
    #         return JsonResponse({'success': False, 'error': str(e)}, status=500)
    
    #@staticmethod
    
    
    # def guardar_datos_backend(request):
    #     if request.method == 'POST':
    #         selected_index = request.POST.get('selected_index')
            
    #         # Procesar y guardar los datos según tus necesidades

    #         # Devolver una respuesta (en este caso, solo un mensaje de éxito)
    #         return JsonResponse({'success': True})
    #     else:
    #         # Devolver una respuesta indicando un método no permitido
    #         return JsonResponse({'success': False, 'error': 'Método no permitido'}, status=405)
    
    
    
    # def form_valid(self, form):
    #     if form.is_valid():
    #         nuevo_simulador = form.save(commit=False)
    #         nuevo_simulador.save()
    #         return super().form_valid(form)
    #     else:
    #         print(form.errors)  # Muestra los errores del formulario en la consola
    #         return super().form_invalid(form)
    
    # def form_valid(self, form):
    #     print('Formulario es válido')
        
    #     #tipo_prestamo = Prestamo.objects.first()  
        
    #     #tipo_prestamo = Prestamo.objects.filter(monto=monto_seleccionado).first()

templates/dashboard/productos/editar-grupal.html
<!-- <h1>plazo</h1>

<!-- <form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Guardar</button>
</form> -->

{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal actualizar</h4>
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <form
      method="POST"
      enctype="multipart/form-data"
      action="{% url 'dashboard_app:editar_grupal' object.id %}"
    >
      {% csrf_token %}
      <div class="modal-body">
        <h1>Editar credito grupal</h1>

        {{form.nombre_grupal.label}} {{form.nombre_grupal}} 
        {{form.numero_participante.label}} {{form.numero_participante}} 
        {{form.monto_credito.label}}{{form.monto_credito}}

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-bsdismiss="modal">
            Cerrar
          </button>
          
          <button type="submit" class="btn btn-primary">Editar</button>
        </div>
      </div>
    </form>
  </div>
</div>

templates/dashboard/productos/editar-productos.html
<!-- <h1>plazo</h1>

<!-- <form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Guardar</button>
</form> -->

{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal actualizar</h4>
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <form
      method="POST"
      enctype="multipart/form-data"
      action="{% url 'dashboard_app:editar_productos' object.id %}"
    >
      {% csrf_token %}
      <div class="modal-body">
        <h1>Productos</h1>

        {{form.nombre_credito.label_tag}} {{form.nombre_credito}}

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-bsdismiss="modal">
            Cerrar
          </button>
          
          <button type="submit" class="btn btn-primary">Editar</button>
        </div>
      </div>
    </form>
  </div>
</div>

templates/dashboard/productos/eliminar-productos.html
{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal eliminar</h4>
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <h4 class="text-secondary">
      ¿Está seguro de que desea eliminar este producto?
    </h4>
    <form
      method="post"
      action="{% url 'dashboard_app:eliminar_productos' object.id %}"
    >
      {% csrf_token %}
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cerrar
        </button>
        
        <button type="submit" class="btn btn-primary">Eliminar</button>
      </div>
    </form>
  </div>
</div>

templates/dashboard/productos/nuevo-grupal.html
{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal title</h4>
       
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <form
      method="POST"
      action="{% url 'dashboard_app:nuevo_grupal' %}"
      enctype="multipart/form-data"
    >
        {% csrf_token %}
        <div class="modal-body">
        <h1>Grupales</h1>
        {{form.nombre_grupal.label}} {{form.nombre_grupal}} 
        {{form.numero_participante.label}} {{form.numero_participante}} 
        {{form.monto_credito.label}}{{form.monto_credito}}
            
        <!-- <button type="submit" class="btn btn-primary">Save changes</button> -->

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
            Cerrar
            </button>
            
            <button type="submit" class="btn btn-primary">Crear</button>
        </div>
        </div>
    </form>
  </div>
</div>

templates/dashboard/productos/nuevo-prestamo.html
{% load static %}

<div class="modal-dialog " aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Crear Prestamo</h4>
       
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <form
      method="POST"
      action="{% url 'dashboard_app:nuevo_productos' %}"
      enctype="multipart/form-data"
    >
        {% csrf_token %}
        <div class="modal-body">
       
        <div class="w-100">
          {{ form.as_p }}
        </div>
            
        <!-- <button type="submit" class="btn btn-primary">Save changes</button> -->

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
            Cerrar
            </button>
            
            <button type="submit" class="btn btn-primary">Crear</button>
        </div>
        </div>
    </form>
  </div>
</div>

templates/dashboard/productos/nuevo-producto.html
{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal title</h4>
       
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <form
      method="POST"
      action="{% url 'dashboard_app:nuevo_productos' %}"
      enctype="multipart/form-data"
    >
        {% csrf_token %}
        <div class="modal-body">
        <h1>Productos</h1>
        {{form.nombre_credito.label_tag}} {{form.nombre_credito}}
            
        <!-- <button type="submit" class="btn btn-primary">Save changes</button> -->

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
            Cerrar
            </button>
            
            <button type="submit" class="btn btn-primary">Crear</button>
        </div>
        </div>
    </form>
  </div>
</div>