applications/dashboard/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard_app'

urlpatterns = [
    path("",views.DashboardView.as_view(), name="index"),
    #path("crear_simulador/<int:user_id>/", views.DashboardView.as_view(), name="crear_simulador"),
    path('preguntas-respuestas/',views.PreguntasRespuestas.as_view(),name='preguntas_respuestas'),
    path('productos/productos-gral/',views.ProductosView.as_view(),name='productos_gral'),
    
    ##### Grupal ####
    path("dashboard/productos/nuevo-grupal/",views.CreateGrupal.as_view(),name="nuevo_grupal"),
    path('dashboard/productos/editar-grupal/<int:pk>/',views.EditarGrupal.as_view(),name='editar_grupal'),
    ##### Grupal ####
    
    ##### producto #####
    path("dashboard/productos/nuevo-producto/",views.CreateProductosView.as_view(),name="nuevo_productos"),
    path('dashboard/productos/editar-productos/<int:pk>/',views.EditarProducto.as_view(),name='editar_productos'),
    path('dashboard/productos/eliminar-productos/<int:pk>/',views.EliminarProducto.as_view(),name='eliminar_productos'),
    
    ##### producto #####
    ##### plazo #####
    path("dashboard/plazos/nuevo-plazo/", views.CreatePlazoView.as_view(), name="nuevo_plazo"),
    path("dashboard/plazos/editar-plazo/<int:pk>/", views.EditarPlazoView.as_view(), name="editar_plazo"),
    path("dashboard/plazos/eliminar-plazo/<int:pk>", views.EliminarPlazo.as_view(), name="eliminar_plazo"),
    ##### plazo #####
    
    ##### obtener el interes ###
    path('obtener-interes/', views.obtener_interes, name='obtener_interes'),
    path('obtener-mora/', views.obtener_moratorio, name='obtener_mora'),
    path('obtener-plazo/', views.obtener_plazo, name='obtener_plazo'),
    ##### obtener el interes ###
    
    path("editar-usuario/<int:pk>", views.EditarUsuarioUsers.as_view(), name="editar_usuario"),
    path("terminos/", views.AvisoPrivacidad.as_view(), name="terminos_condiciones"),
    path("terminos-condiciones/", views.TerminosCondiciones.as_view(), name="terminos_condiciones_2"),
    
    path('pdf-documento/', views.PdfDocument.as_view(), name='pdf_documento'),
    
    path('generar_pdf/', views.PdfDocumentGrupal.as_view(), name='generar_pdf'),
    
    path('mifiel/', views.crearMifiel, name='mifiel'),
    
    path('info-buro/',views.InfoBuro.as_view(),name='info-buro'),
    path('guardar-firma/<int:user_id>/', views.guardar_firma, name='guardar_firma'),
    
    path('nuevo_prestamo/', views.PrestamoCreateView.as_view(), name='nuevo_prestamo'),
    path('sim_prestamo/', views.SimPrestamoCreateView.as_view(), name='sim_prestamo'),
    path('simulador_pruebas/', views.SimuladorPruebaCreateView.as_view(), name='simulador_pruebas'),
    path('pruebas_simula/', views.PruebaSimulaView.as_view(), name='pruebas_simula'),
    path('dashboard/get_nombre_producto/<int:prestamo_id>/', views.GetNombreProductoView.as_view(), name='get_nombre_producto'),
    
    path('csv/', views.DatoView.as_view(), name='csv'),
    path('csv/upload', views.subir_csv, name='subir_csv'),
    
    #path('dashboard/get_nombre_producto/<int:prestamo_id>/', views.GetNombreProductoView.as_view(), name='get_nombre_producto'),
    #path('index/info-prestamo/', views.obtener_informacion_prestamo, name='info_prestamo'),
    #path('dashboard/obtener_detalles_prestamo/', views.ObtenerDetallesPrestamoView.as_view(), name='obtener_detalles_prestamo'),
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/landing/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'landing_app'

urlpatterns = [
    path('',views.landing_view, name='landing')
]

yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
# from yaab_corp.view import index_view
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path('solicitud/',include('applications.credit_personal.urls')),
    path("calificaciones/", include('applications.calificaciones.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/dashboard/views.py
from django.forms import BaseModelForm
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.views import View
from django.views.decorators.http import require_POST,require_GET
from django.db import IntegrityError
from django.http import HttpResponseBadRequest

import base64
from django.core.files.base import ContentFile

from django.views.generic import TemplateView
from django.views.generic import ListView,UpdateView,CreateView,DeleteView
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404

from django.urls import reverse_lazy,reverse
from django.template.loader import get_template
from django.http import FileResponse
from datetime import datetime
import locale

from .models import Productos,Plazo,Simulador,ImageYaab,ProductoCreditoGrupal,Prestamo,SimuladorPrueba,PruebaSimula,Dato
from .forms import ProductosForm,PlazoPagoForm,SimuladorForm,FormProductosGrupal,PrestamoForm,SimPruebas,SimuladorPruebaForm,PruebaSimulaForms,DatoForm

from applications.users.models import User,GrupoCreditoPersonal,CorreosCreditoGrupal
from applications.users.mixins import ValidarPermisosMixin
from applications.users.forms import UserChangeForm
from .utils import render_to_pdf,crearMifiel
from mifiel import Document, Client

import uuid
import logging



# Create your views here.from django.views.generic.base import TemplateView
class DashboardView(LoginRequiredMixin,CreateView):
    model = SimuladorPrueba
    template_name="dashboard/index.html"
    form_class = SimPruebas #SimuladorForm
    success_url = reverse_lazy('dashboard_app:index')
    
    def form_valid(self, form):
        # Asignar el usuario logeado al campo usuario_user antes de guardar
        form.instance.usuario_user = self.request.user
        return super().form_valid(form)
    
class GetNombreProductoView(View):
    def get(self, request, prestamo_id, *args, **kwargs):
        prestamo = get_object_or_404(Prestamo, id=prestamo_id)
        nombre_producto = prestamo.nombre_producto
        tipo_prestamo_nombre = prestamo.tipo_prestamo.tipo_credito if prestamo.tipo_prestamo else None
        tipo_periodo = prestamo.tipo_periodo.periodo_credito if prestamo.tipo_periodo else None
        plazo = prestamo.plazo
        interes_ordinario = prestamo.interes_ordinario
        interes_moratorio = prestamo.interes_moratorio
        pago_mensual = prestamo.pago_mensual
        return JsonResponse({'nombre_producto': nombre_producto,'tipo_prestamo':tipo_prestamo_nombre,'tipo_periodo': tipo_periodo,'plazo':plazo,'interes_ordinario':interes_ordinario,'interes_moratorio':interes_moratorio,'pago_mensual':pago_mensual})





##el bueno##
# class DashboardView(CreateView):
#     template_name="dashboard/index.html"
#     form_class = SimuladorForm
#     success_url = reverse_lazy('dashboard_app:index')
    
#     def get_context_data(self, **kwargs):
#         context = super(DashboardView, self).get_context_data(**kwargs)
#         user = self.kwargs.get('pk')
#         #user_id = self.kwargs.get('pk')
#         #user_id = self.kwargs.get('user_id')
#         #print("Valor de user_id:", user_id)
#         context['pk'] = user
#         context['simula'] = Simulador.objects.filter(id=user)
        

#         return context
    
#     def form_valid(self, form):
        
#         # user_id = self.kwargs.get('user_id')
#         # usuario_actual = get_object_or_404(User, pk=user_id)
        
#         tipo_credito = form.cleaned_data['tipo_credito']
#         plazo_nombre = form.cleaned_data['plazo_nombre']
#         amount = form.cleaned_data['amount']
#         interest_rate = form.cleaned_data['interest_rate']
#         term = form.cleaned_data['term']

#         # Realiza el cálculo
#         monthly_interest_rate = (interest_rate / 12) / 100
#         num_payments = term * 12
#         monthly_payment = (amount * monthly_interest_rate) / (1 - (1 + monthly_interest_rate) ** -num_payments) + (amount / 12) 

#         # Guarda los resultados en la base de datos o donde lo necesites
#         # Aquí se asume que hay un modelo Loan para guardar los resultados
        
#         loan = Simulador(amount=amount, tipo_credito = tipo_credito,plazo_nombre=plazo_nombre, interest_rate=interest_rate, term=term, monthly_payment=monthly_payment)
#         loan.save()
        
#         # url_crear_simulador = reverse('crear_simulador', kwargs={'user_id': user_id})
        
#         # # Guarda el simulador asociándolo al usuario actual
#         # simulador = Simulador.objects.create(
#         #     tipo_credito=tipo_credito,
#         #     plazo_nombre=plazo_nombre,
#         #     amount=amount,
#         #     interest_rate=interest_rate,
#         #     term=term,
#         #     monthly_payment=monthly_payment
#         # )
#         # usuario_actual.simulador = simulador
#         # usuario_actual.save()

#         response_data = {'monthly_payment': monthly_payment}
#         return JsonResponse(response_data)

# class DashboardView(LoginRequiredMixin,CreateView):
#     model = SimuladorPrueba
#     template_name="dashboard/index.html"
#     form_class = SimPruebas #SimuladorForm
#     success_url = reverse_lazy('dashboard_app:index')
    
    
#     def form_valid(self, form):
#         # Guarda la instancia de SimuladorPrueba y asocia el simulador al usuario
#         response = super().form_valid(form)
#         self.object.usuario = self.request.user
#         self.object.save()

#         # Puedes agregar un mensaje si lo deseas
#         messages.success(self.request, 'Simulador guardado exitosamente.')

#         return response
    
    
         
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['montos_prestamo'] = Prestamo.objects.values_list('monto', flat=True)
#         context['prestamos'] = Prestamo.objects.select_related('tipo_prestamo').all().order_by('id')
#         context['tabla_prestamos'] = Prestamo.objects.all()
        
#         return context

#checar esto despues
# class GetNombreProductoView(View):
#     def get(self, request, prestamo_id, *args, **kwargs):
#         prestamo = get_object_or_404(Prestamo, id=prestamo_id)
#         nombre_producto = prestamo.nombre_producto
#         tipo_prestamo_nombre = prestamo.tipo_prestamo.tipo_credito if prestamo.tipo_prestamo else None
#         return JsonResponse({'nombre_producto': nombre_producto,'tipo_prestamo':tipo_prestamo_nombre})
    
    
    # def post(self, request, *args, **kwargs):
    #     try:
    #         # Puedes procesar el índice y realizar otras acciones aquí
    #         selected_index = int(request.POST.get('selected_index'))

    #         # Intenta acceder a la instancia de Prestamo según el índice
    #         prestamo_instance = Prestamo.objects.get(id=selected_index)

    #         # Crea una instancia de tu modelo y guárdala
    #         simulador_prueba = SimuladorPrueba(nombre_prestamo=prestamo_instance)
    #         simulador_prueba.save()

    #         return JsonResponse({'success': True})
    #     except Prestamo.DoesNotExist:
    #         # Maneja el caso donde el Prestamo con el índice dado no existe
    #         return JsonResponse({'success': False, 'error': 'Prestamo no encontrado'}, status=404)
    #     except Exception as e:
    #         # Maneja otras excepciones generales
    #         return JsonResponse({'success': False, 'error': str(e)}, status=500)
    
    # def form_valid(self, form):
    #     try:
    #         # Puedes procesar el índice y realizar otras acciones aquí
    #         selected_index = int(self.request.POST.get('selected_index'))

    #         # Intenta acceder a la instancia de Prestamo según el índice
    #         prestamo_instance = Prestamo.objects.get(id=selected_index)

    #         # Crea una instancia de tu modelo y guárdala
    #         simulador_prueba = SimuladorPrueba(nombre_prestamo=prestamo_instance)
    #         simulador_prueba.save()

    #         return JsonResponse({'success': True})
    #     except Prestamo.DoesNotExist:
    #         # Maneja el caso donde el Prestamo con el índice dado no existe
    #         return JsonResponse({'success': False, 'error': 'Prestamo no encontrado'}, status=404)
    #     except Exception as e:
    #         # Maneja otras excepciones generales
    #         return JsonResponse({'success': False, 'error': str(e)}, status=500)
    
    #@staticmethod
    
    
    # def guardar_datos_backend(request):
    #     if request.method == 'POST':
    #         selected_index = request.POST.get('selected_index')
            
    #         # Procesar y guardar los datos según tus necesidades

    #         # Devolver una respuesta (en este caso, solo un mensaje de éxito)
    #         return JsonResponse({'success': True})
    #     else:
    #         # Devolver una respuesta indicando un método no permitido
    #         return JsonResponse({'success': False, 'error': 'Método no permitido'}, status=405)
    
    
    
    # def form_valid(self, form):
    #     if form.is_valid():
    #         nuevo_simulador = form.save(commit=False)
    #         nuevo_simulador.save()
    #         return super().form_valid(form)
    #     else:
    #         print(form.errors)  # Muestra los errores del formulario en la consola
    #         return super().form_invalid(form)
    
    # def form_valid(self, form):
    #     print('Formulario es válido')
        
    #     #tipo_prestamo = Prestamo.objects.first()  
        
    #     #tipo_prestamo = Prestamo.objects.filter(monto=monto_seleccionado).first()

templates/dashboard/aviso-privacidad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,300&display=swap" rel="stylesheet">

    <title>Aviso|Privacidad</title>
</head>

<style>
    body{
        background-color: #EBEFF2;
        font-family: 'Roboto', sans-serif;
    }
</style>
<body>
    <div class="row mx-auto ">
        <div class="col-10 mx-auto ">
            <p class="fw-bolder pt-5" >
                Los titulares de los datos personales tienen el derecho de conocer sobre el tratamiento que se les dará a los datos proporcionados a YAAB, mediante los Avisos de Privacidad que se encuentran en el acceso de cada inmueble de la Institución y a través de los medios electrónicos por los que se recaben datos personales, a fin de que puedan tomar decisiones informadas al respecto.
            </p>

            <h2>
                Conoce los avisos de privacidad de las Unidades de Negocio de YAAB
            </h2>

            <h5>
                Políticas de protección de datos personales
            </h5>
            <br>
            <h5 class="">
                YAAB está comprometido con la protección de los datos personales que le sean proporcionados, en términos de la Ley General de Protección de Datos Personales en Posesión de Sujetos Obligados.

                Por lo anterior, en cumplimiento a la citada Ley, ponemos a disposición nuestros Avisos de Privacidad, a fin de que los titulares de los datos personales conozcan el tratamiento que se dará a los mismos y puedan tomar decisiones informadas al respecto.

                YAAB podrá hacer modificaciones a los Avisos de Privacidad, de las cuales informaremos aquí sobre cualquier cambio, por lo que sugerimos visitar con frecuencia esta área del sitio para informarse con oportunidad.
            </h5>
            <br>

            <h4 class="text-center fw-bold">AVISO DE PRIVACIDAD INTEGRAL</h4>
            <br>
            <h5>
                YAAB con domicilio en Roble, No. 525, colonia Jardines de Irapuato, Irapuato, C.P. 36660, Guanajuato; es el responsable del tratamiento de los datos personales que recabe, los cuales serán salvaguardados de conformidad con la Ley General de Protección de Datos Personales en Posesión de Sujetos Obligados (LGPDPPSO), y demás normatividad que resulte aplicable.
            </h5>
            <br>

            <p class="fw-bolder">¿Cuáles son las finalidades de recabar sus datos personales?</p>
            <p class="fw-bolder">Los datos personales que se recaben serán utilizados con el objeto de:</p>
            <ul class="fw-bolder">
                <li>Poder brindarte los beneficios correspondientes cuando trate de beneficiarios.</li>
                <li>Para el cumplimiento de la relación contractual derivada de la solicitud y/o contratación de nuestros productos o servicios.</li>
                <li>Verificar, confirmar y validar tu identidad.</li>
                <li>Consultar tu historial crediticio.</li>
                <li>Administrar, operar y dar seguimiento a los servicios y productos solicitados o contratados con YAAB.</li>
                <li>Enviarte notificaciones con la información sobre los productos o servicios contratados.</li>
                <li>Realizar gestiones de cobranza.</li>
                <li>Realizar procesos de auditoría interna y externa.</li>
                <li>Comercializar productos y servicios de YAAB. </li>
                <li>Enviarte ofertas, promociones y publicidad de nuestros productos y servicios.</li>
                <li>Contactarte para invitarte a participar en programas, actividades y eventos organizados por YAAB.</li>
                <li>Elaborar perfiles de clientes para ofrecimiento de productos y servicios bancarios y financieros.</li>
                <li>Realizar encuestas.</li>
            </ul>

            <h6>
                Si no deseás que YAAB trate tus datos personales para alguna de las finalidades descritas en este apartado, podrás solicitarlo enviando un correo electrónico a la siguiente dirección: contacto@yaab.mx
            </h6>
            <br>

            <h5 class="text-dark">¿Qué datos personales se recaban?</h5>
            <h5>
                Para cumplir con las finalidades previstas en el presente Aviso de Privacidad, YAAB recabará la siguiente información:
            </h5>

            <ul>
                <li>Datos de identificación, incluyendo tu imagen.</li>
                <li>Datos de contacto.</li>
                <li>Datos de ubicación.</li>
                <li>Datos laborales.</li>
                <li>Datos académicos.</li>
                <li>Datos patrimoniales y/o financieros.</li>
                <li>Datos biométricos.</li>
            </ul>

            <h4 class="fw-bolder">Transferencia de datos personales </h4>
            <br>
            <h6>
                YAAB podrá transferir tus datos personales tanto a entidades nacionales como extranjeras, sin requerir tu consentimiento en los siguientes supuestos:
            </h6>
            <ul>
                <li>A sociedades de información crediticia para cumplir con obligaciones derivadas de la relación jurídica entre tú y YAAB.</li>
                <li>A autoridades competentes, en ejercicio de sus atribuciones y que estén debidamente fundados y motivados.</li>
                <li>A empresas de mensajería para el envío de comunicaciones relacionadas con los productos y/o servicios contratados.</li>
                <li>A instituciones financieras a efecto de cumplir con la portabilidad y/o movilidad de productos financieros.</li>
            </ul>

            <h6>
                De igual forma, podrán transferirse sus datos personales sin necesidad de requerir el consentimiento de la persona titular, bajo los supuestos establecidos en los artículos 22 y 70 de la LGPDPPSO.
            </h6>
            <h6 class="">Mecanismos, medios y procedimientos disponibles para ejercer los derechos ARCO. </h6>

            <h6>
                Usted puede ejercer sus derechos de acceso, rectificación, cancelación y oposición de datos personales mediante solicitud presentada por los siguientes medios:
            </h6>
            <h6>
                Por correo electrónico en la dirección: contacto@yaab.mx
            </h6>
            <br>
            <h4 class="fw-bolder">Cambios y actualizaciones al Aviso de Privacidad. </h4>
            <h6>
                En caso de que exista un cambio o actualización en el Aviso de Privacidad se pondrá a su disposición en esta misma dirección electrónica: 
            </h6>

            <a href="{% url 'landing_app:landing' %}" target="_blank" style="text-decoration: none; color:black;"> https://www.yaab.mx. </a>
            <br>
            <br>
            <h6>
                No obstante, el aviso de privacidad siempre deberá observar las disposiciones jurídicas aplicables.
            </h6>
            <br><br>

            <h4 class="text-end pb-4 fw-bolder" >
                Fecha de actualización: noviembre 2023
            </h4>


            
        </div>
    </div>


    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>






     
    

templates/dashboard/csv.html
{% extends "dashboard/index.html" %}
<!---->
{% load static %}


{% block content %}
<div class="row">
  <div class="card">
    <h2>Datos</h2>

    <a href="{% url 'dashboard_app:subir_csv' %}" class="btn btn-primary">Subir</a>

    <table class="table table-striped table-hover">
      <thead>
        <th>id</th>
        <th>name</th>
        <th>website</th>
        <th>country</th>
        <th>no. empp.</th>
      </thead>
      <tbody>
        
        {% for o in obj  %}
        <tr>
          <td>{{o.id}}</td>
          <td>{{o.name}}</td>
          <td>{{o.website}}</td>
          <td>{{o.country}}</td>
          <td>{{o.employees}}</td>
        </tr>
        {% endfor %}
          
      
          
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

templates/dashboard/prestamo_form.html
{% extends "partials/layout-vertical.html" %}
<!---->
{% load static %}
<!---->
{%include "partials/topbar.html" with pagetitle="YAAB Servicios Financieros"%}
{% block content %}

<div class="card w-50 p-2">
  <h2>Nuevo Préstamo</h2>
   <form method="post" action="{% url 'dashboard_app:nuevo_prestamo' %}">
     {% csrf_token %}
     {{form.tipo_prestamo.label}}{{form.tipo_prestamo}}
     <br>
     <br>
     {{form.nombre_producto.label}}{{form.nombre_producto}}
     <br>
     {{form.tipo_periodo.label}}{{form.tipo_periodo}}
     <br>
     <br>
     {{form.monto.label}}{{form.monto}}
     <br>
     {{form.plazo.label}}{{form.plazo}}
     <br>
     {{form.interes_ordinario.label}}{{form.interes_ordinario}}
     <br>
     {{form.interes_moratorio.label}}{{form.interes_moratorio}}
     <br>
     {{form.pago_mensual}}
     
     <button type="submit" class="btn btn-secondary">Registrar prestamo</button>
   </form>

</div>
{% endblock content %}

templates/dashboard/upload_csv.html
{% extends "dashboard/index.html" %}
<!---->
{% load static %}


{% block content %}

<div class="container">
    <div class="row">
        <form method="POST" enctype="multipart/form-data" class="form-horizontal" >
            {% csrf_token %}
            <div class="form-group">
                <label for="name"  class="col-md-3 col-sm-3 col-xs-12 control-label " >Archivo: </label>
                <div class="col-md-8">
                    <input type="file" name="csv_file" id="csv_file" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                    <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;">Cargar</span></button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}