applications/landing/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'landing_app'

urlpatterns = [
    path('',views.landing_view, name='landing')
]

applications/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'user_app'


urlpatterns = [
    path('registro/', views.RegistrarUsuario.as_view(), name='registro'),
    path('lista-usuarios/',views.ListaUsuarios.as_view(),name='lista_usuarios'),
    path('eliminar-usuarios/<int:pk>/',views.EliminarUsuarios.as_view(),name='eliminar_usuarios'),
    path('editar-usuarios/<int:pk>/',views.EditarUsuario.as_view(),name='editar_usuarios'),
    path('ubicacion/',views.guardar_ubicacion,name='ubicacion'),
    path('solicitud/<int:user_id>/', views.SolicitudCheck.as_view(), name='solicitud'),
    path('clientes/', views.ClientesAll.as_view(), name='clientes'),
    path('grupal/', views.GrupalCredito.as_view(), name='grupal'),
    path('correo-grupo-credito/', views.correo_grupo_credito, name='correo_grupo_credito'),
    
    path('obtener-monto/', views.obtener_monto, name='obtener_monto'),
    path('formulario-credito/', views.FormularioCreditoGrupal.as_view(), name='formulario_credito'),
    
    path('buro-credito/', views.ModalBruroCredito.as_view(), name='buro_credito'),
    path('aviso-privacidad-grupal/', views.AvisoPrivacidadGrupal.as_view(), name='aviso_privacidad_grupal'),
    path('registrar-credito/', views.RegistrarCreditoView.as_view(), name='registrar_credito'),
    path('carga-masiva/', views.upload_excel_view, name='carga_masiva'),
    
    #path('crear_simulador/<int:user_id>/', views.tu_vista_crear_simulador, name='crear_simulador'),
    
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
# from yaab_corp.view import index_view
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path('solicitud/',include('applications.credit_personal.urls')),
    path("calificaciones/", include('applications.calificaciones.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

applications/users/models.py
from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from applications.dashboard.models import ProductoCreditoGrupal,Simulador,SimuladorPrueba,Prestamo
from django.utils import timezone
from datetime import timedelta,datetime
import numpy as np

class User(AbstractUser):
    
    # *************datos personales ***********
    email = models.EmailField(_('enmail adrees'),unique=True)
    username = models.CharField(max_length=150, unique=False, blank=True, null=True)
    password = models.CharField(_('password'), max_length=128,blank=True,null=True)
    edad=models.IntegerField(null=True,blank=True)
    first_name = models.CharField(max_length=30)
    imagen_perfil = models.ImageField(upload_to='perfil/',blank=True,null=True)
    last_name = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    second_name = models.CharField(max_length=30,blank=True,null=True)
    fecha_nac = models.DateField(null=True,blank=True)
    curp_texto = models.CharField(max_length=30,blank=True,null=True)
    curp = models.FileField(upload_to='users/',blank=True,null=True)
    rfc = models.CharField(max_length=30,blank=True,null=True)
    estado_civil = models.CharField(max_length=30,blank=True,null=True)
    genero = models.CharField(max_length=100,blank=True,null=True)
    nacionalidad = models.CharField(max_length=100,blank=True,null=True)
    pais = models.CharField(max_length=100,blank=True,null=True)
    estado = models.CharField(max_length=100,blank=True,null=True)
    empleo = models.CharField(max_length=100,blank=True,null=True)
    numero_dependientes = models.CharField(max_length=100,blank=True,null=True)
    telefono_particular = models.CharField(max_length=100,blank=True,null=True)
    documento_ine = models.FileField(upload_to='users/',blank=True,null=True)
    firma_digital_personal = models.TextField(max_length=500,blank=True, null=True)
    firma_imagen_personal = models.ImageField(upload_to='media/', blank=True, null=True)
     # *************datos personales ***********
     
      # *************direccion ***********
    calle_numero = models.CharField(max_length=100,blank=True,null=True)
    colonia = models.CharField(max_length=100,blank=True,null=True)
    cp = models.CharField(max_length=100,blank=True,null=True)
    ciudad = models.CharField(max_length=100,blank=True,null=True)
    estado_direccion = models.CharField(max_length=100,blank=True,null=True)
    tipo_vivienda = models.CharField(max_length=100,blank=True,null=True)
    años_radicando = models.CharField(max_length=100,blank=True,null=True)
    comprobante_domicilio = models.FileField(upload_to='users/',blank=True,null=True)
    # *************direccion ***********
    
     # *************referencias ***********      
    conyuge_pareja = models.CharField(max_length=100,blank=True,null=True)
    trabajo_conyuge = models.CharField(max_length=100,blank=True,null=True)
    antiguedad_laboral_conyuge = models.CharField(max_length=100,blank=True,null=True)
    telefono_conyuge = models.CharField(max_length=100,blank=True,null=True)
    referencia_personal_conyuge_1 = models.CharField(max_length=100,blank=True,null=True)
    telefono_ref_conyuge_1 = models.CharField(max_length=100,blank=True,null=True)
    referencia_personal_conyuge_2 = models.CharField(max_length=100,blank=True,null=True)
    telefono_ref_conyuge_2 = models.CharField(max_length=100,blank=True,null=True)
    # *************referencias ***********   
       
    # *************datos del comercio *********** 
    nombre_negocio = models.CharField(max_length=100,blank=True,null=True)
    giro = models.CharField(max_length=100,blank=True,null=True)
    inmueble = models.CharField(max_length=100,blank=True,null=True)
    años_antiguedad = models.CharField(max_length=100,blank=True,null=True)
    calle_numero_negocio = models.CharField(max_length=100,blank=True,null=True)
    colonia_negocio = models.CharField(max_length=100,blank=True,null=True)
    cp_negocio = models.CharField(max_length=100,blank=True,null=True)
    ciudad_negocio = models.CharField(max_length=100,blank=True,null=True)
    estado_negocio = models.CharField(max_length=100,blank=True,null=True)
    # *************datos del comercio *********** 
    
    # ************* datos aval *********** 
    
    nombre_aval = models.CharField(max_length=100,blank=True,null=True)
    primer_apellido = models.CharField(max_length=100,blank=True,null=True)
    segundo_apellido = models.CharField(max_length=100,blank=True,null=True)
    fecha_nac_aval = models.DateField(null=True,blank=True)
    curp_aval = models.FileField(upload_to='users/',blank=True,null=True)
    # curp_aval = models.CharField(max_length=100,blank=True,null=True) 
    genero_aval = models.CharField(max_length=100,blank=True,null=True)
    ciudad_aval = models.CharField(max_length=100,blank=True,null=True)
    estado_aval = models.CharField(max_length=100,blank=True,null=True)
    rfc_aval = models.CharField(max_length=100,blank=True,null=True)
    calle_numero_aval = models.CharField(max_length=100,blank=True,null=True)
    colonia_aval = models.CharField(max_length=100,blank=True,null=True)
    cp_aval = models.CharField(max_length=100,blank=True,null=True)
    relacion_titular = models.CharField(max_length=100,blank=True,null=True)
    tipo_vivienda_aval = models.CharField(max_length=100,blank=True,null=True)
    años_radicando_aval = models.CharField(max_length=100,blank=True,null=True)
    lugar_trabajo_aval = models.CharField(max_length=100,blank=True,null=True)
    antiguedad_trabajo_aval = models.CharField(max_length=100,blank=True,null=True)
    celular_aval = models.CharField(max_length=100,blank=True,null=True)
    email_aval = models.CharField(max_length=100,blank=True,null=True)
    telefono_laboral_aval = models.CharField(max_length=100,blank=True,null=True)
    documento_ine_aval = models.FileField(upload_to='users/',blank=True,null=True)
    comprobante_domicilio_aval = models.FileField(upload_to='users/',blank=True,null=True)
    
    # ************* datos aval *********** 
    
    aviso_privacidad = models.BooleanField(default=False,blank=True,null=True)
    solicitud = models.BooleanField(default=False,blank=True,null=True)
    confirmado = models.BooleanField(default=False,blank=True,null=True)
    rechazado = models.BooleanField(default=False,blank=True,null=True)
    buro_credito = models.BooleanField(default=False,blank=True,null=True)
    simulador = models.ForeignKey(Simulador,on_delete=models.CASCADE,related_name='simulador',blank=True,null=True)
    fecha_solicitud = models.DateTimeField(null=True, blank=True)
    fecha_proximo_viernes = models.DateTimeField(null=True, blank=True)
    
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.email
    


    
class Ubicacion(models.Model):
    latitud = models.CharField(max_length=100,blank=True,null=True)
    longitud = models.CharField(max_length=100,blank=True,null=True)
    
    def __str__(self):
        return self.latitud + ' ' + str(self.id)
    
    
class CorreosCreditoGrupal(models.Model):
    participantes_numero = models.ForeignKey(ProductoCreditoGrupal, on_delete=models.CASCADE, related_name='numero_participantes',null=True,blank=True)
    monto_vacantes = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    correo_coordinador = models.CharField(max_length=30,blank=True,null=True)
    correos_participantes = models.TextField()
    names_grupal = models.CharField(max_length=30,blank=True,null=True)
    surnames_grupal = models.CharField(max_length=30,blank=True,null=True)
    curp_texto_grupal = models.CharField(max_length=30,blank=True,null=True)
    rfc_grupal = models.CharField(max_length=30,blank=True,null=True)
    celular_coordinador = models.CharField(max_length=100,blank=True,null=True)
    
    def __str__(self):
        return str(self.names_grupal) + ' ' + str(self.surnames_grupal)
        
    
    def guardar_correos(self, lista_correos,nombres,apellidos,curp,rfc,celular,participantes_id,monto,correo_personal):
        self.correos_participantes = ",".join(lista_correos)
        self.names_grupal = nombres
        self.surnames_grupal = apellidos
        self.curp_texto_grupal = curp
        self.rfc_grupal = rfc
        self.celular_coordinador = celular
        self.participantes_numero = participantes_id
        self.monto_vacantes = monto  
        self.correo_coordinador = correo_personal   
        self.save()
        
        
    
class GrupoCreditoPersonal(models.Model):
    
    email = models.EmailField(unique=False,blank=True,null=True)
    first_name = models.CharField(max_length=30,blank=True,null=True)
    last_name = models.CharField(max_length=30,blank=True,null=True)
    second_name = models.CharField(max_length=30,blank=True,null=True)
    fecha_nac_grupal = models.DateField(null=True,blank=True)
    curp_texto = models.CharField(max_length=30,blank=True,null=True)
    curp = models.FileField(upload_to='users/',blank=True,null=True)
    rfc = models.CharField(max_length=30,blank=True,null=True)
    estado_civil = models.CharField(max_length=30,blank=True,null=True)
    genero = models.CharField(max_length=100,blank=True,null=True)
    nacionalidad = models.CharField(max_length=100,blank=True,null=True)
    pais = models.CharField(max_length=100,blank=True,null=True)
    estado = models.CharField(max_length=100,blank=True,null=True)
    celular = models.CharField(max_length=100,blank=True,null=True)
    numero_dependientes = models.CharField(max_length=100,blank=True,null=True)

templates/users/buro-credito-html.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,300&display=swap"
      rel="stylesheet"
    />

    <title>Aviso|Privacidad</title>
  </head>

  <style>
    body {
      background-color: #ebeff2;
      font-family: "Roboto", sans-serif;
    }
  </style>
  <body>
    <div class="row mx-auto">
      <div class="col-10 mx-auto">
        <div class="text-end">
          <img src="{% static 'images/landing/financiera_logo.png' %}" alt="" />
        </div>

        <h3 class="fw-bolder pt-5 text-center">
          CARTA DE AUTORIZACIÓN PARA LA CONSULTA EN BURÓ DE CRÉDITO
        </h3>
        <hr />

        <p>
          Por este conducto autorizo a YAAB Inversiones y servicios financieros,
          S.A. de C.V. para que lleve a cabo investigaciones sobre el
          comportamiento crediticio de la empresa que represento en las
          Sociedades de Información Crediticia que estime conveniente. Así
          mismo, declaro que conozco la naturaleza y alcance de la información
          que se solicitará, del uso que YAAB Inversiones y servicios
          financieros, S.A. de C.V. hará de tal información y de que esta podrá
          realizar consultas periódicas de su historial crediticio, durante el
          tiempo que mantenga relacion juridica con mi representada. Bajo
          protesta de decir verdad manitiesto SER REPRESENTANTE LEGAL de la
          Empresa mencionada en esta autorización.
        </p>

        <p>
          Estoy consciente y acepto que este documento quede bajo propiedad de
          YAAB Inversiones y servicios financieros, S.A. de C.V. para efectos de
          control y cumplimiento del articulo 28 de la Ley para Regular a Las
          sociedades de información Crediticia.
        </p>

        <p>
          La vigencia de esta autorizacion permanecera mientras exista relacion
          comercial entre el usuario y el cliente.
        </p>

        <!-- <a
          href="{% url 'landing_app:landing' %}"
          target="_blank"
          style="text-decoration: none; color: black"
        >
          https://www.yaab.mx.
        </a>
        <br />
        <br />
        <h6>
          No obstante, el aviso de privacidad siempre deberá observar las
          disposiciones jurídicas aplicables.
        </h6>
        <br /><br /> -->

        <h4 class="text-end pb-4 fw-bolder">
          Fecha de actualización: Enero 2024
        </h4>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/users/credito-grupal.html
{% load static %}
{% load crispy_forms_tags %}
{% load allauth i18n socialaccount %}
{% block head_title %}
    {% trans "" %}
    
{% endblock head_title %}

<!DOCTYPE html>
<html lang="en">

{% include "partials/title-meta.html" with title="Registro | Yaab" %}

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            let cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                let cookie = cookies[i].trim();
                // Buscar el token CSRF
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    let csrftoken = getCookie('csrftoken');
</script>

<style>
  

    .btn-wsp{
        position:fixed;
        width:60px;
        height:60px;
        line-height: 63px;
        bottom:25px;
        right:25px;
        background:#3b3d3c;
        color:#FFF;
        border-radius:50px;
        text-align:center;
        font-size:35px;
        box-shadow: 0px 1px 10px rgba(0,0,0,0.3);
        z-index:100;
        transition: all 300ms ease;
    }
    .btn-wsp:hover{
        background: #d5dbd7;
    }
    @media only screen and (min-width:320px) and (max-width:768px){
        .btn-wsp{
            width:63px;
            height:63px;
            line-height: 66px;
      }
    }
</style>

{% include "partials/head-css.html" %}



<body class="loading " style="background: url('../../static/images/landing/yaab_corp_reg.png'); background-size:cover;"  >

    <div class="account-pages mt-1 mb-2 bg-register"  >
        <div class="container ">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-8 col-xl-8">
                    <div class="text-center">
                        <a href="{% url 'index' %}">
                            <img src="{% static 'images/landing/financiera_logo.png' %}" alt="" width="30%" class="mx-auto">
                        </a>
                        <h3 class="text-light">CRÉDITO GRUPAL</h3>
                        
                    </div>
                </div> <!-- end col -->
            </div>
            <!-- end row -->
             <div class="row">

                <div class="col d-none">
                    <div class="card ">  
                        
                        
                        <!-- <form class="d-none" method="post" action=" url 'account_signup' ">
                                 csrf_token 
                               
                                 signup_form.as_p 
                      
                                
                                
                                <button class="btn btn-secondary" type="submit">Confirmar credito grupal</button>
                        </form> -->
                       
                        <div class="card-body p-4">
                            <h4>Coordinador</h4>

                            
                            <!-- {{correo_form.estado_civil_grupal.label}}{{correo_form.estado_civil_grupal}}
                            {{correo_form.genero_grupal.label}}{{correo_form.genero_grupal}}
                            {{correo_form.nacionalidad_grupal.label}}{{correo_form.nacionalidad_grupal}}
                            {{correo_form.pais_grupal.label}}{{correo_form.pais_grupal}} -->
                            
                            
                            

                            

                        </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                <div class="col-6">
                     <div class="card ">  
                         <form method="post" action="{% url 'user_app:correo_grupo_credito' %}">
                            {% csrf_token %}
                        <div  class="card-body p-4 ">
                            
                            
                            <h4>Registro de integrantes para el crédito grupal:</h4>


                            <p>Ingresar datos del coordinador:</p>
                            <!-- {{ correo_form.as_p }} -->
                            
                            {{correo_form.names_grupal.label}}{{correo_form.names_grupal}}
                            {{correo_form.surnames_grupal.label}}{{correo_form.surnames_grupal}}
                            {{correo_form.correo_coordinador.label}}{{correo_form.correo_coordinador}}
                            
                            {{correo_form.curp_texto_grupal.label}}{{correo_form.curp_texto_grupal}}
                            {{correo_form.rfc_grupal.label}}{{correo_form.rfc_grupal}}
                            {{correo_form.celular_coordinador.label}}{{correo_form.celular_coordinador}}

                            <br>
                           
                           
                            
                            {{correo_form.participantes_numero.label}}{{correo_form.participantes_numero}}
                            {{correo_form.monto_vacantes.label}}{{correo_form.monto_vacantes}}
                            <!-- {{correo_form.email_credito_grupal.label}}{{correo_form.email_credito_grupal}}
                            <h4>Ingresar correos electronicos:</h4>
                            
                            {{correo_form.segundo_email_grupal.label}}{{correo_form.segundo_email_grupal}}
                            {{correo_form.tercero_email_grupal.label}}{{correo_form.tercero_email_grupal}}
                            {{correo_form.cuarto_email_grupal.label}}{{correo_form.cuarto_email_grupal}}
                            {{correo_form.quinto_email_grupal.label}}{{correo_form.quinto_email_grupal}}
                            {{correo_form.sexto_email_grupal.label}}{{correo_form.sexto_email_grupal}}
                            {{correo_form.septimo_email_grupal.label}}{{correo_form.septimo_email_grupal}}
                            {{correo_form.octavo_email_grupal.label}}{{correo_form.octavo_email_grupal}}
                            {{correo_form.noveno_email_grupal.label}}{{correo_form.noveno_email_grupal}}
                            {{correo_form.decimo_email_grupal.label}}{{correo_form.decimo_email_grupal}}
                            {{correo_form.onceavo_email_grupal.label}}{{correo_form.onceavo_email_grupal}} -->
                            
                            <div id="campos_correo_grupal">

                            </div>
                            
                            <button class="btn btn-secondary mt-2" type="submit">Finalizar Registro</button>
                        </form>

                           

                        </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->
                </div>
                        
            </div>

           



                    
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->

        <a href="{% url 'landing_app:landing' %}" class="btn-wsp mb-4" target="_blank">
	    <i class="mdi mdi-home"></i>
	  </a>

    <!-- Vendor -->
    {% include "partials/vendor.html" %}

    <!-- App js -->
    <script src="{% static 'js/app.min.js' %}"></script>

    <script>


        $(document).ready(function () {
            $("#id_participantes_numero").change(function () {
                var selectedProduct = $(this).val();
                
                if (selectedProduct) {
                    // Realiza una solicitud AJAX al servidor para obtener el interés del producto seleccionado
                    $.ajax({
                    url: "{% url 'user_app:obtener_monto' %}", // Reemplaza con la URL correcta
                    data: {
                        monto_id: selectedProduct,
                    },
                    success: function (data) {
                        // Rellena el campo interest_rate con el valor recibido
                        $("#id_monto_vacantes").val(data.interest);
                    },
                    });
                } else {
                    // Borra el campo interest_rate si no hay selección
                    $("#id_monto_vacantes").val("");
                }
            });
        });

        
    </script>

    <script>
        $(document).ready(function () {
            $("#id_participantes_numero").change(function () {
                var selectedParticipants = parseInt($(this).find(":selected").text());
                var camposCorreo = $("#campos_correo_grupal");
                console.log(selectedParticipants)

                // Elimina todos los campos de correo electrónico existentes
                camposCorreo.empty();

                // Crea y muestra los campos correspondientes al número seleccionado
                for (var i = 1; i <= selectedParticipants; i++) {

                    var label = $('<label>',{
                        'for': 'email_' + i + '_grupal',
                        'text': 'Parcticipante ' + i + ':'
                    });

                    var campoEmail = $('<input>', {
                        'type': 'email',
                        'class': 'form-control mb-2',
                        'placeholder': 'correo electrónico...',
                        'id': 'email_' + i + '_grupal',
                        'name': 'email_' + i + '_grupal'
                    });
                    camposCorreo.append(label);
                    camposCorreo.append(campoEmail);
                }
            });
        });

    </script>




<script>
    /*
    $(document).ready(function () {
        $("#id_participantes_numero").change(function () {

            var selectedOption = $(this).find(":selected");
            var selectedParticipants = selectedOption.val();
            //var selectedParticipants = selectedOption.data("data-numero-participante");
            //var selectedParticipants = parseInt($(this).find(":selected").data("numero-participante"));
            //var selectedParticipants = parseInt($(this).find(":selected").text());
            var camposCorreo = $("#campos_correo_grupal");
            console.log(selectedParticipants)
            //console.log(selectedOption)

            // Elimina todos los campos de correo electrónico existentes
            camposCorreo.empty();

            // Crea y muestra los campos correspondientes al número seleccionado
            for (var i = 1; i <= selectedParticipants; i++) {

                var label = $('<label>',{
                    'for': 'email_' + i + '_grupal',
                    'text': 'Participante ' + i + ':'
                });

                var campoEmail = $('<input>', {
                    'type': 'email',
                    'class': 'form-control mb-2',
                    'placeholder': 'correo electrónico...',
                    'id': 'email_' + i + '_grupal',
                    'name': 'email_' + i + '_grupal'
                });
                camposCorreo.append(label);
                camposCorreo.append(campoEmail);
            }
        });
    });
    */

    
</script>
<script>
    //$(document).ready(function () {
    //    $("#id_participantes_numero").change(function () {
    //        var selectedParticipants = parseInt($(this).val());
    //        // Oculta todos los campos de correo electrónico
    //        for (var i = 1; i <= 11; i++) { // Ajusta el límite al número máximo de campos
    //            $("#email_" + i + "_grupal").hide();
    //        }
    //        // Muestra solo los campos de correo electrónico correspondientes al número seleccionado
    //        for (var i = 1; i <= selectedParticipants; i++) {
    //            $("#email_" + i + "_grupal").show();
    //        }
    //    });
    //});
</script>
   
   
</body>

templates/users/eliminar-usuario.html
{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal eliminar</h4>
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <h4 class="text-secondary">
      ¿Está seguro de que desea eliminar este usuario?
    </h4>
    <form
      method="post"
      action="{% url 'user_app:eliminar_usuarios' object.id %}"
    >
      {% csrf_token %}
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cerrar
        </button>
       
        <button type="submit" class="btn btn-primary">Eliminar</button>
      </div>
    </form>
  </div>
</div>

templates/users/upload_excel.html
{% extends "dashboard/index.html" %}
<!---->
{% load static %}


{% block content %}

<h4>Crear usuarios por medio de un Excel</h4>
<p>Nota: Recuerda de no duplicar el correo electronico en tu tabla excel por custiones de duplicidad de usuario.</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit" class="btn btn-secondary">Crear Usuarios</button>
    </form>

{% endblock content %}